services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SCRAPER_API_KEY=${SCRAPER_API_KEY}
      - SCRAPINGBEE_API_KEY=${SCRAPINGBEE_API_KEY}
    # Scripts, input, and output files.
    volumes:
      - ${DATA_PATH}:/app
    restart: unless-stopped
  server:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ${DATA_PATH}:/app
    # Ports do not need exposed when using Traefik.
    # ports:
    #   - ${EXT_PORT}:${INT_PORT}
    command:
      - bash
      - ./run_server.sh
      - ${INT_PORT}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.rates_fetcher.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.http.routers.rates_fetcher.entrypoints=https
      - traefik.http.routers.rates_fetcher.tls=true
      - traefik.http.services.rates_fetcher.loadbalancer.server.port=${INT_PORT}
      - traefik.docker.network=proxy # Required for multiple networks in the stack.
    networks:
      - proxy
networks:
  proxy:
    external: true
